/**
 * Populates a demo customer with submissions in every state so the dashboard
 * and admin queue can be reviewed with realistic content.
 *   npx tsx --conditions=react-server scripts/seed-demo.ts
 */
import { randomBytes } from "node:crypto";
import bcrypt from "bcryptjs";
import { db } from "../src/lib/db";
import { saveFile } from "../src/lib/storage";
import { makeReference } from "../src/lib/utils";
import { createShareLink, shareLinkUrl } from "../src/lib/share-links";

/** Hand-rolled single-page PDF so downloads work without a PDF dependency. */
function tinyPdf(title: string, lines: string[]) {
  const content = [
    "BT /F1 18 Tf 60 740 Td (" + title.replace(/[()\\]/g, "") + ") Tj ET",
    ...lines.map(
      (l, i) =>
        `BT /F1 11 Tf 60 ${700 - i * 20} Td (${l.replace(/[()\\]/g, "")}) Tj ET`,
    ),
  ].join("\n");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefAt = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const o of offsets) pdf += `${String(o).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF`;

  return Buffer.from(pdf, "latin1");
}

async function main() {
  // Not hardcoded: this repo is public, and a known password in source is an
  // invitation to try it against a real deployment. Override via env, or take
  // the random one printed at the end.
  const email = process.env.DEMO_EMAIL || "demo@example.com";
  const password = process.env.DEMO_PASSWORD || randomBytes(9).toString("base64url");

  let user = await db.user.findUnique({ where: { email } });
  if (!user) {
    user = await db.user.create({
      data: {
        email,
        name: "Amina Kariuki",
        phone: "+254 700 123 456",
        passwordHash: await bcrypt.hash(password, 12),
        credits: 8,
        // Both per-customer features on, so the extra tabs are visible.
        featureShareLinks: true,
        featureApi: true,
        partnerName: "Amina's Proofreading",
      },
    });
  } else {
    user = await db.user.update({
      where: { id: user.id },
      data: { featureShareLinks: true, featureApi: true, credits: 8 },
    });
  }

  await db.submission.deleteMany({ where: { userId: user.id } });

  const doc = Buffer.from(
    "Demo document body used to populate the dashboard for review.",
    "utf8",
  );

  const plan: Array<{
    title: string;
    status: string;
    sim?: number;
    ai?: number;
    ageHours: number;
  }> = [
    { title: "Dissertation — chapter 4", status: "COMPLETED", sim: 11.4, ai: 3.2, ageHours: 52 },
    { title: "Literature review draft", status: "COMPLETED", sim: 27.8, ai: 18.5, ageHours: 30 },
    { title: "Methodology section", status: "COMPLETED", sim: 41.2, ai: 62.0, ageHours: 26 },
    { title: "Conference abstract", status: "PROCESSING", ageHours: 2 },
    { title: "Final thesis — full draft", status: "QUEUED", ageHours: 0.4 },
    { title: "Seminar paper", status: "FAILED", ageHours: 70 },
  ];

  for (const p of plan) {
    const stored = await saveFile(`submissions/${user.id}`, `${p.title}.docx`, doc);
    const createdAt = new Date(Date.now() - p.ageHours * 3600_000);
    const completed = p.status === "COMPLETED";

    let simPath: string | null = null;
    let aiPath: string | null = null;
    if (completed) {
      simPath = (
        await saveFile(
          `reports/${user.id}`,
          "similarity.pdf",
          tinyPdf("Similarity Report", [
            `Document: ${p.title}`,
            `Overall similarity: ${p.sim}%`,
            "",
            "Top matched sources:",
            "  1. Journal of Applied Linguistics ......... 4%",
            "  2. University repository ................. 3%",
            "  3. Internet source - jstor.org ........... 2%",
            "",
            "This is demo content generated by seed-demo.ts.",
          ]),
        )
      ).key;
      aiPath = (
        await saveFile(
          `reports/${user.id}`,
          "ai.pdf",
          tinyPdf("AI Writing Report", [
            `Document: ${p.title}`,
            `Estimated AI-generated text: ${p.ai}%`,
            "",
            "This is demo content generated by seed-demo.ts.",
          ]),
        )
      ).key;
    }

    const submission = await db.submission.create({
      data: {
        userId: user.id,
        reference: makeReference(),
        title: p.title,
        fileName: `${p.title}.docx`,
        fileSize: 240_000 + Math.floor(Math.random() * 900_000),
        mimeType:
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        storagePath: stored.key,
        status: p.status,
        similarityScore: p.sim ?? null,
        aiScore: p.ai ?? null,
        wordCount: completed ? 4200 + Math.floor(Math.random() * 6000) : null,
        pageCount: completed ? 14 + Math.floor(Math.random() * 30) : null,
        similarityReportPath: simPath,
        aiReportPath: aiPath,
        failureReason:
          p.status === "FAILED"
            ? "The uploaded file was password protected and could not be opened."
            : null,
        createdAt,
        completedAt: completed ? new Date(createdAt.getTime() + 8 * 60_000) : null,
        purgeAfter: new Date(createdAt.getTime() + 7 * 86400_000),
      },
    });

    const events = [{ status: "QUEUED", message: "Document received and queued for processing." }];
    if (["PROCESSING", "COMPLETED"].includes(p.status))
      events.push({ status: "PROCESSING", message: "Your document is being analysed." });
    if (completed)
      events.push({ status: "COMPLETED", message: "Your reports are ready to download." });
    if (p.status === "FAILED")
      events.push({
        status: "FAILED",
        message: "The uploaded file was password protected and could not be opened.",
      });

    for (const [i, e] of events.entries()) {
      await db.submissionEvent.create({
        data: {
          submissionId: submission.id,
          status: e.status,
          message: e.message,
          createdAt: new Date(createdAt.getTime() + i * 4 * 60_000),
        },
      });
    }
  }

  const messages = await db.contactMessage.count();
  if (messages === 0) {
    await db.contactMessage.createMany({
      data: [
        {
          name: "Joseph Mwangi",
          email: "joseph@example.com",
          subject: "Can I check a PowerPoint?",
          message: "I have a 60-slide deck. Does the similarity check work on PPTX files?",
        },
        {
          name: "Faith Wanjiru",
          email: "faith@example.com",
          subject: "Report not downloading",
          message: "My report shows as ready but the download button does nothing on mobile.",
          status: "READ",
        },
      ],
    });
  }

  const pending = await db.review.count({ where: { status: "PENDING" } });
  if (pending === 0) {
    await db.review.create({
      data: {
        userId: user.id,
        name: "Amina Kariuki",
        rating: 5,
        body: "Fast and clear. The AI report caught a paragraph I had rewritten from a draft and I fixed it before submitting.",
        status: "PENDING",
      },
    });
  }

  await db.shareLink.deleteMany({ where: { ownerId: user.id } });
  const link = await createShareLink(user.id, { label: "Joseph — final year project", allocated: 3 });

  console.log(`\n  Demo customer: ${email} / ${password}`);
  console.log(`  Share link:    ${shareLinkUrl(link.code)}`);
  console.log(`  ${plan.length} submissions across every status.\n`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => db.$disconnect());
